### ISSUE TITLE
Still referencing apollo-accounts-material-ui

### ISSUE THREAD

**Issue by aarmand** [js-accounts/apollo-accounts-example#3]
In <https://github.com/js-accounts/apollo-accounts-example/blob/master/ui/index.js> you try to this import. Looks like your meaning to update to react-material-ui....FYI

```
import Accounts from 'apollo-accounts-react-material-ui';
```
Build is failing as a result.

**Comment by TimMikeladze** [comment]
Thanks for opening an issue but I'm afraid this repository is deprecated and I will be deleting it along with all the other apollo-* named ones.
